:num_workers:             4
:default_worker_wait:     1
:max_worker_wait:         20
:worker_wait_multiplier:  1.3
:worker_retry_wait:       5
:work_unit_retries:       3
:central_server:          http://localhost:9173
:s3_bucket:               cloud_crowd_development

:db:
  :adapter:               mysql
  :encoding:              utf8
  :username:              root
  :password:
  :socket:                /tmp/mysql.sock
  :database:              cloud_crowd_development
  
# add a work_unit_timeout really big
# actions can override