:num_workers:             4
:default_worker_wait:     1
:max_worker_wait:         20
:worker_wait_multiplier:  1.3
:worker_retry_wait:       5
:work_unit_retries:       3

:central_server:          http://localhost:9173
:authentication:          no
:login:                   [your login name]
:hashed_password:         [the SHA1 hash of your chosen password]

:s3_bucket:               [your CloudCrowd bucket]
:aws_access_key:          [your AWS access key]
:aws_secret_key:          [your AWS secret access key]
