defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password:
  socket: /tmp/mysql.sock
  
development:
  <<: *defaults
  database: dogpile_development
  
test:
  <<: *defaults
  database: dogpile_test
    
production:
  <<: *defaults
  database: dogpile_production
  password: master
