defaults: &defaults
  autoscale:                  no
  num_workers:                4
  default_worker_sleep_time:  1
  max_worker_sleep_time:      20
  worker_sleep_multiplier:    1.3

development:
  <<: *defaults
  central_server: http://localhost:3000
  s3_bucket:      dogpile_development
                  
test:             
  <<: *defaults   
  central_server: http://localhost:3000
  s3_bucket:      dogpile_test
  
production:
  <<: *defaults
  central_server: http://dogpile.ec2.webco.com
  s3_bucket:      dogpile_production