development:
  central_server:             http://localhost:3000
  s3_bucket:                  dogpile_development
  num_workers:                4
  default_worker_sleep_time:  1
  max_worker_sleep_time:      20
  worker_sleep_multiplier:    1.3