defaults: &defaults
  num_workers:            4
  default_worker_wait:    1
  max_worker_wait:        20
  worker_wait_multiplier: 1.3
  worker_retry_wait:      5

development:
  <<: *defaults
  central_server: http://localhost:9173
  s3_bucket:      dogpile_development
                  
test:             
  <<: *defaults   
  central_server: http://localhost:9173
  s3_bucket:      dogpile_test
  
production:
  <<: *defaults
  central_server: http://dogpile.ec2.webco.com
  s3_bucket:      dogpile_production