defaults: &defaults
  aws_access_key: AKIAILH45M5OFUTSFEZQ
  aws_secret_key: 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

development:
  <<: *defaults
  
test:
  <<: *defaults

production:
  <<: *defaults
